export const CATEGORY_LABELS: Record<string, string> = {
  SHELTER: "Приюты для животных",
  ELDERLY: "Помощь пожилым",
  PSO: "Поиск пропавших (ПСО)",
  URBAN: "Благоустройство городов",
};

export const CATEGORY_SHORT: Record<string, string> = {
  SHELTER: "Животные",
  ELDERLY: "Пожилые",
  PSO: "Поиск людей",
  URBAN: "Благоустройство",
};

export const CATEGORY_ORDER = ["SHELTER", "ELDERLY", "PSO", "URBAN"] as const;

export const CATEGORY_COLORS: Record<string, string> = {
  SHELTER: "bg-amber-100 text-amber-800",
  ELDERLY: "bg-sky-100 text-sky-800",
  PSO: "bg-rose-100 text-rose-800",
  URBAN: "bg-emerald-100 text-emerald-800",
};

export const STATUS_LABELS: Record<string, string> = {
  PENDING: "На рассмотрении",
  APPROVED: "Одобрено",
  REJECTED: "Отклонено",
  DONE: "Выполнено",
  NO_SHOW: "Не явился",
};

export const STATUS_COLORS: Record<string, string> = {
  PENDING: "bg-yellow-100 text-yellow-800",
  APPROVED: "bg-green-100 text-green-800",
  REJECTED: "bg-red-100 text-red-800",
  DONE: "bg-blue-100 text-blue-800",
  NO_SHOW: "bg-rose-100 text-rose-800",
};

export const OPPORTUNITY_STATUS_LABELS: Record<string, string> = {
  OPEN: "Набор открыт",
  CLOSED: "Набор закрыт",
  COMPLETED: "Завершено",
};

export const OPPORTUNITY_STATUS_COLORS: Record<string, string> = {
  OPEN: "bg-green-100 text-green-800",
  CLOSED: "bg-gray-200 text-gray-700",
  COMPLETED: "bg-blue-100 text-blue-800",
};

export type CategoryKey = (typeof CATEGORY_ORDER)[number];

export const BELARUS_CITIES = [
  "Брест",
  "Витебск",
  "Гомель",
  "Гродно",
  "Минск",
  "Могилёв",
  "Барановичи",
  "Бобруйск",
  "Борисов",
  "Жлобин",
  "Жодино",
  "Лида",
  "Мозырь",
  "Молодечно",
  "Новополоцк",
  "Орша",
  "Пинск",
  "Полоцк",
  "Речица",
  "Светлогорск",
  "Слуцк",
  "Солигорск",
  "Марьина Горка",
  "Несвиж",
  "Кобрин",
  "Дзержинск",
  "Сморгонь",
  "Глубокое",
  "Ивацевичи",
  "Лунинец",
  "Новогрудок",
  "Осиповичи",
  "Волковыск",
  "Калинковичи",
  "Рогачёв",
  "Кричев",
  "Добруш",
  "Горки",
  "Слоним",
  "Береза",
  "Житковичи",
  "Костюковичи",
  "Чаусы",
  "Мстиславль",
  "Ошмяны",
  "Поставы",
  "Верхнедвинск",
  "Браслав",
  "Крупки",
  "Белыничи",
  "Чериков",
  "Славгород",
  "Хойники",
  "Петриков",
  "Дрогичин",
  "Каменец",
  "Пружаны",
  "Малорита",
  "Шклов",
  "Быхов",
  "Кировск",
  "Климовичи",
  "Клецк",
  "Столбцы",
  "Логойск",
  "Заславль",
  "Фаниполь",
  "Смолевичи",
  "Червень",
  "Старые Дороги",
  "Узда",
  "Любань",
  "Копыль",
  "Вилейка",
  "Мядель",
  "Докшицы",
  "Шарковщина",
  "Миоры",
  "Толочин",
  "Чашники",
  "Лепель",
  "Сенно",
  "Городок",
  "Дубровно",
  "Буда-Кошелёво",
  "Ветка",
  "Чечерск",
  "Корма",
  "Брагин",
  "Наровля",
  "Ельск",
  "Лельчицы",
  "Лоев",
  "Октябрьский",
  "Краснополье",
  "Глуск",
  "Бобр",
  "Хотимск",
  "Кругляны",
  "Дрибин",
  "Городея",
  "Мир",
  "Ивье",
  "Дятлово",
  "Вороново",
  "Островец",
  "Щучин",
  "Зельва",
  "Мосты",
  "Берёзовка",
  "Скидель",
  "Кореличи",
  "Новая Мышь",
] as const;
